# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(600, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(LoginForm)
        self.label.setStyleSheet("font-size: 14px; color: #333;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.usernameLineEdit = QtWidgets.QLineEdit(LoginForm)
        self.usernameLineEdit.setStyleSheet("font-size: 14px; padding: 10px; border: 1px solid #ccc; border-radius: 5px; background-color: #fff;")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.label_2 = QtWidgets.QLabel(LoginForm)
        self.label_2.setStyleSheet("font-size: 14px; color: #333;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginForm)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setStyleSheet("font-size: 14px; padding: 10px; border: 1px solid #ccc; border-radius: 5px; background-color: #fff;")
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.rememberMeCheckBox = QtWidgets.QCheckBox(LoginForm)
        self.rememberMeCheckBox.setStyleSheet("font-size: 12px; color: #333;")
        self.rememberMeCheckBox.setObjectName("rememberMeCheckBox")
        self.verticalLayout.addWidget(self.rememberMeCheckBox)
        self.loginButton = QtWidgets.QPushButton(LoginForm)
        self.loginButton.setStyleSheet("font-size: 14px; padding: 10px; background-color: #800000; color: white; border: none; border-radius: 5px;")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        self.faceRecognitionButton = QtWidgets.QPushButton(LoginForm)
        self.faceRecognitionButton.setStyleSheet("font-size: 14px; padding: 10px; background-color: #800000; color: white; border: none; border-radius: 5px;")
        self.faceRecognitionButton.setObjectName("faceRecognitionButton")
        self.verticalLayout.addWidget(self.faceRecognitionButton)
        self.videoLabel = QtWidgets.QLabel(LoginForm)
        self.videoLabel.setText("")
        self.videoLabel.setMinimumSize(QtCore.QSize(480, 360))
        self.videoLabel.setObjectName("videoLabel")
        self.verticalLayout.addWidget(self.videoLabel)
        self.forgotPasswordButton = QtWidgets.QPushButton(LoginForm)
        self.forgotPasswordButton.setStyleSheet("font-size: 12px; color: #800000; background: none; border: none;")
        self.forgotPasswordButton.setObjectName("forgotPasswordButton")
        self.verticalLayout.addWidget(self.forgotPasswordButton)
        self.needHelpButton = QtWidgets.QPushButton(LoginForm)
        self.needHelpButton.setStyleSheet("font-size: 12px; color: #800000; background: none; border: none;")
        self.needHelpButton.setObjectName("needHelpButton")
        self.verticalLayout.addWidget(self.needHelpButton)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "MacEwan University"))
        self.label.setText(_translate("LoginForm", "MacEwan Username"))
        self.label_2.setText(_translate("LoginForm", "Password"))
        self.rememberMeCheckBox.setText(_translate("LoginForm", "Remember this login for 10 hours"))
        self.loginButton.setText(_translate("LoginForm", "Login"))
        self.faceRecognitionButton.setText(_translate("LoginForm", "Face Recognition Login"))
        self.forgotPasswordButton.setText(_translate("LoginForm", "Forgot your password?"))
        self.needHelpButton.setText(_translate("LoginForm", "Need help?"))
