# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 791)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:rgb(247, 251, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerWidget = QtWidgets.QWidget(self.widget)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.headerWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(123, 3, 35);\n"
"    border: 0px solid rgb(0,0,0);\n"
"    border-bottom-left-radius : 50px; \n"
"    border-bottom-right-radius : 50px;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    height:30px;\n"
"    text-align:center;\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    color:white;\n"
"    text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #34111a;\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(344, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.headerWidget)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        self.label_8.setStyleSheet("text-align:centre;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/user.svg"))
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.userDropMenuButton = QtWidgets.QPushButton(self.headerWidget)
        self.userDropMenuButton.setMinimumSize(QtCore.QSize(35, 35))
        self.userDropMenuButton.setMaximumSize(QtCore.QSize(35, 35))
        self.userDropMenuButton.setStyleSheet("QPushButton{\n"
"    border: 0px solid grey;\n"
"    border-radius: 15px;\n"
"\n"
"}")
        self.userDropMenuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userDropMenuButton.setIcon(icon)
        self.userDropMenuButton.setIconSize(QtCore.QSize(20, 20))
        self.userDropMenuButton.setCheckable(True)
        self.userDropMenuButton.setAutoExclusive(True)
        self.userDropMenuButton.setObjectName("userDropMenuButton")
        self.horizontalLayout_2.addWidget(self.userDropMenuButton)
        self.verticalLayout.addWidget(self.headerWidget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.attendancePage = QtWidgets.QWidget()
        self.attendancePage.setObjectName("attendancePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.attendancePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.attendancePage)
        self.scrollArea.setStyleSheet("background-color:  rgb(247, 251, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1162, 673))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_2.setStyleSheet("QWidget{\n"
"    background-color:rgb(247, 251, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(59,59,59);\n"
"    color: white;\n"
"    height:30px;\n"
"    text-align:left;\n"
"    border: none;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"    border-bottom-left-radius:5px;\n"
"    border-top-left-radius:5px;\n"
"    border-bottom-right-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:  rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.attendancePage_classNameLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.attendancePage_classNameLabel.setFont(font)
        self.attendancePage_classNameLabel.setStyleSheet("")
        self.attendancePage_classNameLabel.setObjectName("attendancePage_classNameLabel")
        self.horizontalLayout_3.addWidget(self.attendancePage_classNameLabel)
        spacerItem2 = QtWidgets.QSpacerItem(670, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.dateSelectorButton = QtWidgets.QPushButton(self.frame)
        self.dateSelectorButton.setMinimumSize(QtCore.QSize(0, 40))
        self.dateSelectorButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.dateSelectorButton.setObjectName("dateSelectorButton")
        self.horizontalLayout_3.addWidget(self.dateSelectorButton)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.takeAttendanceButton = QtWidgets.QPushButton(self.frame_3)
        self.takeAttendanceButton.setMinimumSize(QtCore.QSize(0, 40))
        self.takeAttendanceButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.takeAttendanceButton.setObjectName("takeAttendanceButton")
        self.horizontalLayout_4.addWidget(self.takeAttendanceButton)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.manageStudentsAttendanceButton = QtWidgets.QPushButton(self.frame_4)
        self.manageStudentsAttendanceButton.setMinimumSize(QtCore.QSize(0, 40))
        self.manageStudentsAttendanceButton.setMaximumSize(QtCore.QSize(16777215, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/edit-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageStudentsAttendanceButton.setIcon(icon1)
        self.manageStudentsAttendanceButton.setIconSize(QtCore.QSize(30, 30))
        self.manageStudentsAttendanceButton.setObjectName("manageStudentsAttendanceButton")
        self.horizontalLayout_5.addWidget(self.manageStudentsAttendanceButton)
        spacerItem4 = QtWidgets.QSpacerItem(795, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.studentsAttendanceGrid = QtWidgets.QGridLayout()
        self.studentsAttendanceGrid.setObjectName("studentsAttendanceGrid")
        self.horizontalLayout_6.addLayout(self.studentsAttendanceGrid)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.attendancePage)
        self.attendanceCapturePage = QtWidgets.QWidget()
        self.attendanceCapturePage.setObjectName("attendanceCapturePage")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.attendanceCapturePage)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_9 = QtWidgets.QWidget(self.attendanceCapturePage)
        self.widget_9.setMaximumSize(QtCore.QSize(640, 900))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_12.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.camera_interface = QtWidgets.QWidget(self.widget_9)
        self.camera_interface.setMaximumSize(QtCore.QSize(640, 480))
        self.camera_interface.setStyleSheet("background-color: rgb(210, 219, 255);")
        self.camera_interface.setObjectName("camera_interface")
        self.verticalLayout_12.addWidget(self.camera_interface)
        self.attendance_status = QtWidgets.QWidget(self.widget_9)
        self.attendance_status.setMaximumSize(QtCore.QSize(640, 100))
        self.attendance_status.setStyleSheet("background-color: rgb(216, 255, 252);")
        self.attendance_status.setObjectName("attendance_status")
        self.verticalLayout_12.addWidget(self.attendance_status)
        self.horizontalLayout_9.addWidget(self.widget_9)
        self.camera_on_button = QtWidgets.QPushButton(self.attendanceCapturePage)
        self.camera_on_button.setMaximumSize(QtCore.QSize(100, 20))
        self.camera_on_button.setObjectName("camera_on_button")
        self.horizontalLayout_9.addWidget(self.camera_on_button)
        self.camera_off_button = QtWidgets.QPushButton(self.attendanceCapturePage)
        self.camera_off_button.setMaximumSize(QtCore.QSize(100, 20))
        self.camera_off_button.setIconSize(QtCore.QSize(5, 5))
        self.camera_off_button.setObjectName("camera_off_button")
        self.horizontalLayout_9.addWidget(self.camera_off_button)
        self.stackedWidget.addWidget(self.attendanceCapturePage)
        self.manageStudentsPage = QtWidgets.QWidget()
        self.manageStudentsPage.setObjectName("manageStudentsPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.manageStudentsPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.manageStudentsPage)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_16 = QtWidgets.QWidget(self.widget_2)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setStyleSheet("QPushButton{\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color: #b3b3b3;\n"
"}")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem5 = QtWidgets.QSpacerItem(1051, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.addStudentButton_3 = QtWidgets.QPushButton(self.widget_17)
        self.addStudentButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.addStudentButton_3.setMaximumSize(QtCore.QSize(100, 40))
        self.addStudentButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/blackIcons/BlackIcons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addStudentButton_3.setIcon(icon2)
        self.addStudentButton_3.setIconSize(QtCore.QSize(40, 40))
        self.addStudentButton_3.setObjectName("addStudentButton_3")
        self.horizontalLayout_16.addWidget(self.addStudentButton_3)
        self.verticalLayout_20.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.widget_16)
        self.widget_18.setStyleSheet("QLineEdit{\n"
"    padding-left:10px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color: #b3b3b3;\n"
"}")
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_18)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_17.addWidget(self.lineEdit_3)
        self.studentSearchButton = QtWidgets.QPushButton(self.widget_18)
        self.studentSearchButton.setMinimumSize(QtCore.QSize(0, 40))
        self.studentSearchButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.studentSearchButton.setObjectName("studentSearchButton")
        self.horizontalLayout_17.addWidget(self.studentSearchButton)
        spacerItem6 = QtWidgets.QSpacerItem(818, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.refreshbutton = QtWidgets.QPushButton(self.widget_18)
        self.refreshbutton.setMinimumSize(QtCore.QSize(0, 40))
        self.refreshbutton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.refreshbutton.setObjectName("refreshbutton")
        self.horizontalLayout_17.addWidget(self.refreshbutton)
        self.verticalLayout_20.addWidget(self.widget_18)
        self.verticalLayout_7.addWidget(self.widget_16)
        self.widget_15 = QtWidgets.QWidget(self.widget_2)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.widget_15)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1144, 509))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.studentsViewGridLayout = QtWidgets.QGridLayout()
        self.studentsViewGridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.studentsViewGridLayout.setSpacing(10)
        self.studentsViewGridLayout.setObjectName("studentsViewGridLayout")
        self.gridLayout_3.addLayout(self.studentsViewGridLayout, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_2.addWidget(self.scrollArea_4, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.widget_15)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.manageStudentsPage)
        self.manageClassesPage = QtWidgets.QWidget()
        self.manageClassesPage.setObjectName("manageClassesPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.manageClassesPage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.manageClassesPage)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.widget_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_8 = QtWidgets.QWidget(self.frame_6)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(578, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_11.addWidget(self.widget_8)
        self.widget_7 = QtWidgets.QWidget(self.frame_6)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_7.setStyleSheet("QLineEdit{\n"
"    padding-left:10px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color: #b3b3b3;\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_7)
        self.lineEdit.setMinimumSize(QtCore.QSize(500, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(500, 40))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.searchCoursesButton = QtWidgets.QPushButton(self.widget_7)
        self.searchCoursesButton.setMinimumSize(QtCore.QSize(0, 40))
        self.searchCoursesButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.searchCoursesButton.setObjectName("searchCoursesButton")
        self.horizontalLayout_10.addWidget(self.searchCoursesButton)
        spacerItem8 = QtWidgets.QSpacerItem(398, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.addCourseButton = QtWidgets.QPushButton(self.widget_7)
        self.addCourseButton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.addCourseButton.setText("")
        self.addCourseButton.setIcon(icon2)
        self.addCourseButton.setIconSize(QtCore.QSize(30, 30))
        self.addCourseButton.setAutoExclusive(True)
        self.addCourseButton.setObjectName("addCourseButton")
        self.horizontalLayout_10.addWidget(self.addCourseButton)
        self.verticalLayout_11.addWidget(self.widget_7)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.widget_51 = QtWidgets.QWidget(self.widget_3)
        self.widget_51.setObjectName("widget_51")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_51)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.widget_51)
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setStyleSheet("QPushButton{\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"   background-color: #b3b3b3;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        spacerItem9 = QtWidgets.QSpacerItem(1072, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.refreshCoursesButton = QtWidgets.QPushButton(self.widget_6)
        self.refreshCoursesButton.setMinimumSize(QtCore.QSize(0, 40))
        self.refreshCoursesButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.refreshCoursesButton.setObjectName("refreshCoursesButton")
        self.horizontalLayout_8.addWidget(self.refreshCoursesButton)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_51)
        self.scrollArea_2.setStyleSheet("\n"
"QPushButton{\n"
"    height:30px;\n"
"    text-align:center;\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #ffffff;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1126, 458))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.coursesGridLayout = QtWidgets.QGridLayout()
        self.coursesGridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.coursesGridLayout.setSpacing(10)
        self.coursesGridLayout.setObjectName("coursesGridLayout")
        self.horizontalLayout_11.addLayout(self.coursesGridLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.verticalLayout_8.addWidget(self.widget_51)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.manageClassesPage)
        self.reportsPage = QtWidgets.QWidget()
        self.reportsPage.setObjectName("reportsPage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.reportsPage)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_4 = QtWidgets.QWidget(self.reportsPage)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_17.addWidget(self.label_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 653, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem10)
        self.verticalLayout_16.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.reportsPage)
        self.profilePage = QtWidgets.QWidget()
        self.profilePage.setObjectName("profilePage")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.profilePage)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_13 = QtWidgets.QWidget(self.profilePage)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_18.setSpacing(17)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_10 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_18.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_18.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14)
        spacerItem11 = QtWidgets.QSpacerItem(20, 557, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem11)
        self.horizontalLayout_15.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.profilePage)
        self.widget_14.setStyleSheet("background-color:rgb(247, 251, 255);")
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_19.setSpacing(8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_19.addWidget(self.lineEdit_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_19.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_19.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_19.addWidget(self.lineEdit_6)
        spacerItem12 = QtWidgets.QSpacerItem(20, 557, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem12)
        self.horizontalLayout_15.addWidget(self.widget_14)
        self.stackedWidget.addWidget(self.profilePage)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "App Name"))
        self.label_9.setText(_translate("MainWindow", "Welcome Back, User"))
        self.attendancePage_classNameLabel.setText(_translate("MainWindow", "Attendance: Class Name"))
        self.dateSelectorButton.setText(_translate("MainWindow", "Date Selector"))
        self.takeAttendanceButton.setText(_translate("MainWindow", "Take Attendance"))
        self.manageStudentsAttendanceButton.setText(_translate("MainWindow", "Manage Students"))
        self.camera_on_button.setText(_translate("MainWindow", "Turn On"))
        self.camera_off_button.setText(_translate("MainWindow", "Turn Off"))
        self.label_15.setText(_translate("MainWindow", "Your Students"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Find Student ..."))
        self.studentSearchButton.setText(_translate("MainWindow", "Search"))
        self.refreshbutton.setText(_translate("MainWindow", "Refresh"))
        self.label_5.setText(_translate("MainWindow", "Dashboard"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Find Course ..."))
        self.searchCoursesButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Your Classes:"))
        self.refreshCoursesButton.setText(_translate("MainWindow", "Refresh"))
        self.label_3.setText(_translate("MainWindow", "Reports"))
        self.label_10.setText(_translate("MainWindow", "User Name"))
        self.label_12.setText(_translate("MainWindow", "Department Name"))
        self.label_13.setText(_translate("MainWindow", "Password"))
        self.label_14.setText(_translate("MainWindow", "Email"))
import backgoundImages_rc
import icons_rc
