# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 766)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuIcons = QtWidgets.QWidget(self.centralwidget)
        self.menuIcons.setMinimumSize(QtCore.QSize(100, 0))
        self.menuIcons.setStyleSheet("QWidget{\n"
"    background-color: rgb(59,59,59);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(59,59,59);\n"
"    color: white;\n"
"    height:30px;\n"
"    border:none;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-left-radius:10px;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:  rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}\n"
"QLabel{\n"
"    color:white;\n"
"    text-align:center;\n"
"}")
        self.menuIcons.setObjectName("menuIcons")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.menuIcons)
        self.verticalLayout_5.setContentsMargins(6, -1, 0, -1)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(89, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.menuIcons)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logo/LOGO/whiteLogo.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.attendanceMenuIconButton = QtWidgets.QPushButton(self.menuIcons)
        self.attendanceMenuIconButton.setMinimumSize(QtCore.QSize(0, 50))
        self.attendanceMenuIconButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.attendanceMenuIconButton.setIcon(icon)
        self.attendanceMenuIconButton.setCheckable(True)
        self.attendanceMenuIconButton.setAutoExclusive(True)
        self.attendanceMenuIconButton.setObjectName("attendanceMenuIconButton")
        self.verticalLayout_5.addWidget(self.attendanceMenuIconButton)
        self.manageStudentsMenuIconButton = QtWidgets.QPushButton(self.menuIcons)
        self.manageStudentsMenuIconButton.setMinimumSize(QtCore.QSize(0, 50))
        self.manageStudentsMenuIconButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/users.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageStudentsMenuIconButton.setIcon(icon1)
        self.manageStudentsMenuIconButton.setCheckable(True)
        self.manageStudentsMenuIconButton.setAutoExclusive(True)
        self.manageStudentsMenuIconButton.setObjectName("manageStudentsMenuIconButton")
        self.verticalLayout_5.addWidget(self.manageStudentsMenuIconButton)
        self.manageClassesMenuIconButton = QtWidgets.QPushButton(self.menuIcons)
        self.manageClassesMenuIconButton.setMinimumSize(QtCore.QSize(0, 50))
        self.manageClassesMenuIconButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/archive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageClassesMenuIconButton.setIcon(icon2)
        self.manageClassesMenuIconButton.setCheckable(True)
        self.manageClassesMenuIconButton.setAutoExclusive(True)
        self.manageClassesMenuIconButton.setObjectName("manageClassesMenuIconButton")
        self.verticalLayout_5.addWidget(self.manageClassesMenuIconButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 322, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButton_10 = QtWidgets.QPushButton(self.menuIcons)
        self.pushButton_10.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon3)
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setAutoExclusive(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_5.addWidget(self.pushButton_10)
        self.horizontalLayout.addWidget(self.menuIcons)
        self.menuLabels = QtWidgets.QWidget(self.centralwidget)
        self.menuLabels.setMinimumSize(QtCore.QSize(200, 0))
        self.menuLabels.setStyleSheet("QWidget{\n"
"    background-color: rgb(59,59,59);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(59,59,59);\n"
"    color: white;\n"
"    height:30px;\n"
"    text-align:left;\n"
"    border: none;\n"
"    padding-left:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:  rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:white;\n"
"    text-align:center;\n"
"}")
        self.menuLabels.setObjectName("menuLabels")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menuLabels)
        self.verticalLayout_4.setContentsMargins(6, -1, 0, -1)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem2)
        self.widget_5 = QtWidgets.QWidget(self.menuLabels)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setMinimumSize(QtCore.QSize(100, 100))
        self.label_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Logo/LOGO/whiteLogo.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.attendanceMenuLabelButton = QtWidgets.QPushButton(self.menuLabels)
        self.attendanceMenuLabelButton.setMinimumSize(QtCore.QSize(0, 50))
        self.attendanceMenuLabelButton.setIcon(icon)
        self.attendanceMenuLabelButton.setCheckable(True)
        self.attendanceMenuLabelButton.setAutoExclusive(True)
        self.attendanceMenuLabelButton.setObjectName("attendanceMenuLabelButton")
        self.verticalLayout_4.addWidget(self.attendanceMenuLabelButton)
        self.manageStudentsMenuLabelButton = QtWidgets.QPushButton(self.menuLabels)
        self.manageStudentsMenuLabelButton.setMinimumSize(QtCore.QSize(0, 50))
        self.manageStudentsMenuLabelButton.setIcon(icon1)
        self.manageStudentsMenuLabelButton.setCheckable(True)
        self.manageStudentsMenuLabelButton.setAutoExclusive(True)
        self.manageStudentsMenuLabelButton.setObjectName("manageStudentsMenuLabelButton")
        self.verticalLayout_4.addWidget(self.manageStudentsMenuLabelButton)
        self.manageClassesMenuLabelButton = QtWidgets.QPushButton(self.menuLabels)
        self.manageClassesMenuLabelButton.setMinimumSize(QtCore.QSize(0, 50))
        self.manageClassesMenuLabelButton.setIcon(icon2)
        self.manageClassesMenuLabelButton.setCheckable(True)
        self.manageClassesMenuLabelButton.setAutoExclusive(True)
        self.manageClassesMenuLabelButton.setObjectName("manageClassesMenuLabelButton")
        self.verticalLayout_4.addWidget(self.manageClassesMenuLabelButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 322, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_15 = QtWidgets.QPushButton(self.menuLabels)
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setAutoExclusive(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_4.addWidget(self.pushButton_15)
        self.horizontalLayout.addWidget(self.menuLabels)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerWidget = QtWidgets.QWidget(self.widget)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.headerWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(123, 3, 35);\n"
"\n"
"}\n"
"QPushButton{\n"
"    color:white;\n"
"    height:30px;\n"
"    text-align:center;\n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    color:white;\n"
"    text-align:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #34111a;\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.headerWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_12.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_12.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.label_6 = QtWidgets.QLabel(self.headerWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(344, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(self.headerWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_8 = QtWidgets.QLabel(self.headerWidget)
        self.label_8.setMinimumSize(QtCore.QSize(30, 30))
        self.label_8.setStyleSheet("text-align:centre;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/user.svg"))
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.pushButton_16 = QtWidgets.QPushButton(self.headerWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_16.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_16.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/whiteIcons/whiteIcons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon5)
        self.pushButton_16.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_2.addWidget(self.pushButton_16)
        self.verticalLayout.addWidget(self.headerWidget, 0, QtCore.Qt.AlignVCenter)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.attendancePage = QtWidgets.QWidget()
        self.attendancePage.setObjectName("attendancePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.attendancePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.attendancePage)
        self.scrollArea.setStyleSheet("background-color:  rgb(255, 255, 255); ")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 874, 666))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(59,59,59);\n"
"    color: white;\n"
"    height:30px;\n"
"    text-align:left;\n"
"    border: none;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"    border-bottom-left-radius:5px;\n"
"    border-top-left-radius:5px;\n"
"    border-bottom-right-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:  rgb(52,17,26);\n"
"    color: white;\n"
"    font-weight:bold;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(670, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.dateSelectorButton = QtWidgets.QPushButton(self.frame)
        self.dateSelectorButton.setObjectName("dateSelectorButton")
        self.horizontalLayout_3.addWidget(self.dateSelectorButton)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.subjectSelectButton = QtWidgets.QComboBox(self.frame_3)
        self.subjectSelectButton.setStyleSheet("background-color: rgb(222, 215, 255);")
        self.subjectSelectButton.setEditable(False)
        self.subjectSelectButton.setCurrentText("")
        self.subjectSelectButton.setObjectName("subjectSelectButton")
        self.horizontalLayout_4.addWidget(self.subjectSelectButton)
        self.courseNameSelectButton = QtWidgets.QComboBox(self.frame_3)
        self.courseNameSelectButton.setStyleSheet("background-color: rgb(222, 215, 255);")
        self.courseNameSelectButton.setEditable(False)
        self.courseNameSelectButton.setCurrentText("")
        self.courseNameSelectButton.setObjectName("courseNameSelectButton")
        self.horizontalLayout_4.addWidget(self.courseNameSelectButton)
        self.sectionSelectButton = QtWidgets.QComboBox(self.frame_3)
        self.sectionSelectButton.setStyleSheet("background-color: rgb(222, 215, 255);")
        self.sectionSelectButton.setEditable(False)
        self.sectionSelectButton.setCurrentText("")
        self.sectionSelectButton.setObjectName("sectionSelectButton")
        self.horizontalLayout_4.addWidget(self.sectionSelectButton)
        spacerItem7 = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.takeAttendanceButton = QtWidgets.QPushButton(self.frame_3)
        self.takeAttendanceButton.setObjectName("takeAttendanceButton")
        self.horizontalLayout_4.addWidget(self.takeAttendanceButton)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sortByButton = QtWidgets.QPushButton(self.frame_4)
        self.sortByButton.setObjectName("sortByButton")
        self.horizontalLayout_5.addWidget(self.sortByButton)
        spacerItem8 = QtWidgets.QSpacerItem(795, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.widget_51 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_51.setObjectName("widget_51")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_51)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.widget_51)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.attendancePage)
        self.manageStudentsPage = QtWidgets.QWidget()
        self.manageStudentsPage.setObjectName("manageStudentsPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.manageStudentsPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.manageStudentsPage)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.manageStudentsPage)
        self.ManageClassesPage = QtWidgets.QWidget()
        self.ManageClassesPage.setObjectName("ManageClassesPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ManageClassesPage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.ManageClassesPage)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.ManageClassesPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.attendanceMenuLabelButton.toggled['bool'].connect(self.attendanceMenuIconButton.setChecked) # type: ignore
        self.pushButton_10.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton_15.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.attendanceMenuIconButton.toggled['bool'].connect(self.attendanceMenuLabelButton.setChecked) # type: ignore
        self.manageClassesMenuLabelButton.toggled['bool'].connect(self.manageClassesMenuIconButton.setChecked) # type: ignore
        self.manageClassesMenuIconButton.toggled['bool'].connect(self.manageClassesMenuLabelButton.setChecked) # type: ignore
        self.pushButton_10.toggled['bool'].connect(self.pushButton_15.setChecked) # type: ignore
        self.manageStudentsMenuIconButton.toggled['bool'].connect(self.manageStudentsMenuLabelButton.setChecked) # type: ignore
        self.manageStudentsMenuLabelButton.toggled['bool'].connect(self.manageStudentsMenuIconButton.setChecked) # type: ignore
        self.pushButton_15.toggled['bool'].connect(self.pushButton_10.setChecked) # type: ignore
        self.pushButton_12.toggled['bool'].connect(self.menuIcons.setHidden) # type: ignore
        self.pushButton_12.toggled['bool'].connect(self.menuLabels.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Sidebar"))
        self.attendanceMenuLabelButton.setText(_translate("MainWindow", "Take Attendance"))
        self.manageStudentsMenuLabelButton.setText(_translate("MainWindow", "Manage Students"))
        self.manageClassesMenuLabelButton.setText(_translate("MainWindow", "Manage Classes"))
        self.pushButton_15.setText(_translate("MainWindow", "Sign Out"))
        self.label_6.setText(_translate("MainWindow", "Menu"))
        self.label_7.setText(_translate("MainWindow", "App Name"))
        self.label_4.setText(_translate("MainWindow", "Attendance"))
        self.dateSelectorButton.setText(_translate("MainWindow", "Date Selector"))
        self.takeAttendanceButton.setText(_translate("MainWindow", "Take Attendance"))
        self.sortByButton.setText(_translate("MainWindow", "Sort by:"))
        self.label_3.setText(_translate("MainWindow", "Manage Students"))
        self.label_5.setText(_translate("MainWindow", "Manage Classes  Page"))
import backgoundImages_rc
import icons_rc
